FROM debian:12

RUN apt-get update && apt-get install nginx -y openssl

RUN mkdir -p /etc/nginx/ssl
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/deimos.crt \            
	-keyout /etc/nginx/ssl/deimos.key \
	-subj "/C=mr/ST=IDF/L=benguerir/O=1337/OU=1337/CN=deimos.42.fr/UID=iszitoun"

COPY config/default /etc/nginx/sites-enabled/default


CMD [ "nginx" , "-g" , "daemon off;" ] 
