FROM debian:12

RUN apt-get update && apt-get install -y \
    php-fpm \
    php-mysql \
    wget

RUN wget https://fr.wordpress.org/wordpress-6.0-fr_FR.tar.gz -P /var/www \
    && cd /var/www \
    && tar -xzf wordpress-6.0-fr_FR.tar.gz \
    && rm wordpress-6.0-fr_FR.tar.gz

RUN chown -R www-data:www-data /var/www/wordpress

COPY ./tools/config.sh /

RUN chmod +x /config.sh

CMD ["sh", "/config.sh"]